### ISSUE TITLE
Publications.rss throws exception

### ISSUE THREAD

**Issue by meshuggahtas** [adelikat/tasvideos#522]
Link:
https://tasvideos.mistflux.net/Publications.rss

```
An unhandled exception occurred while processing the request.

System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.Average(IEnumerable`1 source)
   at TASVideos.Pages.RssFeeds.Models.RssPublication.get_RatingAverage() in /home/tasvideos/tasvideos/TASVideos/Pages/RssFeeds/Models/RssPublication.cs:line 37
   at TASVideos.Pages.RssFeeds.Pages_RssFeeds__RssPublication.ExecuteAsync() in /home/tasvideos/tasvideos/TASVideos/Pages/RssFeeds/_RssPublication.cshtml:line 35
```

**Comment by meshuggahtas** [comment]
Still throws exception but it's currently a bit different.

```
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.Min[TSource](IEnumerable`1 source, Func`2 selector)
   at TASVideos.Pages.RssFeeds.Models.RssPublication.get_RatingMin() in /home/tasvideos/tasvideos/TASVideos/Pages/RssFeeds/Models/RssPublication.cs:line 22
   at TASVideos.Pages.RssFeeds.Pages_RssFeeds__RssPublication.ExecuteAsync() in /home/tasvideos/tasvideos/TASVideos/Pages/RssFeeds/_RssPublication.cshtml:line 35
```

**Comment by adelikat** [comment]
Fixed
